export const jobsCard = [
  // {
  //   Name: "apple",
  //   Location: "Location : Bengaluru",
  //   Qualification: " Qualification : Bachelor",
  //   Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
  //   Salary: "Salary : Up to 6 LPA (Expected)",
  //   Experience: "Experience : Fresher",
  //   link: "",
  // },
  // {
  //   Name: "apple",
  //   Location: "Location : Bengaluru",
  //   Qualification: " Qualification : Bachelor",
  //   Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
  //   Salary: "Salary : Up to 6 LPA (Expected)",
  //   Experience: "Experience : Fresher",
  //   link: "",
  // },
  // {
  //   Name: "apple",
  //   Location: "Location : Bengaluru",
  //   Qualification: " Qualification : Bachelor",
  //   Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
  //   Salary: "Salary : Up to 6 LPA (Expected)",
  //   Experience: "Experience : Fresher",
  //   link: "",
  // },
  // {
  //   Name: "apple",
  //   Location: "Location : Bengaluru",
  //   Qualification: " Qualification : Bachelor",
  //   Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
  //   Salary: "Salary : Up to 6 LPA (Expected)",
  //   Experience: "Experience : Fresher",
  //   link: "",
  // },
  {
    Name: "KPMG Recruitment For Data Management – Analyst",
    Location: "Location : Across India",
    Qualification: " Qualification : B.E / B.Tech / M.E / M.Tech / MBA / MCA",
    Batch: "Batch : 2025 ",
    Experience: "Experience : Freshers / Experienced",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/INTG10025229?utm_source=jobscoupe.com",
  },
  {
    Name: "Peroptyx Recruitment For Data Analyst",
    Location: "Location : Work From Home",
    Qualification: " Qualification : Undergraduate / Graduate",
    Batch: "Batch : 2025 ",
    Experience: "Experience : 0 – 5 Years",
    link: "https://www.naukri.com/job-listings-data-analyst-english-required-peroptyx-delhi-ncr-0-to-5-years-200524003834?utm_source=jobscoupe.com",
  },
  {
    Name: "Zeotap Recruitment For Data Science – Intern",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : B.E / B.Tech / M.E / M.Tech",
    Batch: "Batch : 2025 ",
    Experience: "Experience : Fresher",
    link: "https://jobs.lever.co/zeotap/fcbef23e-0bf4-4312-89b5-634f89d169e9?utm_source=jobscoupe.com",
  },
  {
    Name: "ZS Associates Recruitment For Business Technology Solutions Associate",
    Location: "Location : Pune",
    Qualification: " Qualification : Bachelor’s / Master’s Degree",
    Batch: "Batch : 2025 ",
    Experience: "Experience : 0 – 3 Years",
    link: "https://jobs.zs.com/all/jobs/21048?lang=en-us&utm_source=jobscoupe.com",
  },
  {
    Name: "Goldman Sachs Recruitment For New Analyst",
    Location: "Location : Bangalore / Hyderabad",
    Qualification: " Qualification : Undergraduate / Graduate ",
    Batch: "Batch : 2025 ",
    Experience: "Experience : Fresher",
    link: "https://hdpc.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CampusHiring/job/128287?utm_source=jobscoupe.com",
  },
  {
    Name: "Equifax Recruitment For Software Engineer – Trainee",
    Location: "Location : Mumbai",
    Qualification: " Qualification : B.E / B.Tech / M.E / M.Tech / MCA",
    Batch: "Batch : 2024 ",
    Experience: "Experience : Fresher",
    link: "https://careers.equifax.com/en/jobs/j00163747/software-engineer-trainee/?utm_source=jobscoupe.com",
  },
  {
    Name: "Myntra Recruitment For Associate",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelor’s Degree",
    Batch: "Batch : 2025 ",
    Experience: "Experience : 1 – 2 Years",
    link: "https://job-boards.greenhouse.io/myntra/jobs/7789124002?source=jobscoupe.com",
  },
  {
    Name: "HCLTech Hiring Fresher Drive 2024 For Graduate Trainee",
    Location: "Location : Lucknow/Nagpur",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to ₹ 7 LPA",
    Experience: "Experience : Fresher",
    link: "https://forms.office.com/pages/responsepage.aspx?id=N-edGDrJWk-LaG9MqZQZElCAazGQaRZGsk4ipyNb95tUMzhOTEhTNk80TjIxODAwQkxKOEtLS1lERC4u&route=shorturl",
  },
  {
    Name: "YASH Technologies Hiring For Fresher Drive 2024 | For Trainee Consultant – SAP",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : Bachelor’s/Master’s Degree",
    Batch: "Batch : Recent Batches",
    Salary: "Salary : Up to ₹ 7 LPA",
    Experience: "Experience : Fresher",
    link: "https://careers.yash.com/job/Hyderabad-SAP-Trainee-Consultant-Job/1058662366/",
  },
  {
    Name: "Accenture Hiring For Web Developer",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelors / Masters Degree",
    Batch: "Batch : 2021, 2022, 2023 & 2024 ",
    Salary: "Salary : Up to ₹ 7 LPA",
    Experience: "Experience : Fresher",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4720648-S1830560_en",
  },
  {
    Name: "TCS BSc Ignite and Smart Hiring – Batch of 2025",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : BCA, B.Sc, B.Voc",
    Batch: "Batch : 2025 ",
    Salary: "Salary : 	Up to ₹ 4.1 LPA",
    Experience: "Experience : Fresher",
    link: "https://www.tcs.com/careers/india/tcs-bsc-ignite-and-smart-hiring-2025?utm_source=Whatsapp&utm_medium=banner&utm_campaign=BSC+Ignite",
  },
  {
    Name: "Capgemini Off Campus Drive 2024 For Deal Centre of Excellence",
    Location: "Location : Mumbai",
    Qualification: " Qualification : B Com and BAF",
    Batch: "Batch : 2024 ",
    Salary: "Salary : Up to ₹ 4 LPA",
    Experience: "Experience : Fresher",
    link: "https://www.capgemini.com/in-en/solutions/off-campus-drive-for-deal-centre-of-excellence-dcoe-2024-graduates/",
  },

  {
    Name: "Genpact Hiring Fresher Drive 2024 For Management Trainee",
    Location: "Location : Mumbai",
    Qualification: " Qualification : MBA Finance (With B Com in Graduation)",
    Batch: "Batch : 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : As Per Company Standard",
    Experience: "Experience : Fresher",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=BFS037677",
  },
  {
    Name: "Atos Off Campus Drive 2024 | For Any Graduate, Location Across India",
    Location: "Location : Across India",
    Qualification: " Qualification : Any Graduation",
    Batch: "Batch : Any Batches ",
    Salary: "Salary : Up to 5 LPA (Expected)",
    Experience: "Experience : Fresher (0 – 2)",
    link: "https://atos.net/en/india/campus-recruitment-form",
  },
  {
    Name: "Genpact Hiring Fresher Drive 2024 For Management Trainee – Python Developer",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : Bachelor’s Degree",
    Batch: "Batch : Any Batches ",
    Salary: "Salary : Up to ₹ 8 LPA",
    Experience: "Experience : Fresher",
    link: "https://unstop.com/jobs/management-trainee-python-developer-genpact-1066328?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=Genpact11072024&ref=Prepflix",
  },
  {
    Name: "QualiTlabs Recruitment 2024 For Software Developer – Trainee",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : B.E / B.Tech",
    Experience: "Experience : Fresher",
    link: "https://www.naukri.com/job-listings-software-developer-trainee-hyderabad-b-tech-freshers-qualitlabs-hyderabad-0-to-1-years-250624010112?utm_source=jobscoupe.com",
  },
  {
    Name: "Harman Careers Hiring for Associate Test Automation",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelor",
    Batch: "Batch : 2024 ",
    Experience: "Experience : Freshers & Experience",
    link: "https://jobs.harman.com/en_US/careers/JobDetail/Associate-Test-Automation/22973",
  },
  {
    Name: "Amazon Off Campus Recruitment Drive 2024",
    Location: "Location : Chennai",
    Qualification: " Qualification : Bachelor",
    Batch: "Batch : 2021/ 2022/ 2023/ 2024 ",
    Experience: "Experience : Freshers & Experience",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/ju0f4/apply/?j=56434&e=12271",
  },
  {
    Name: "Ericsson Careers Hiring for Associate Engineer Trainee",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelor’s/Master’s Degree",
    Batch: "Batch : Recent Batches",
    Salary: "Salary : Up to 6.3 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://jobs.ericsson.com/careers/job/563121759980810?domain=ericsson.com",
  },
  {
    Name: "IBM is hiring for Technical Support Engineer",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelor’s/Master’s Degree",
    Batch: "Batch : Recent Batches ",
    Salary: "Salary : Up to 7.6 LPA (Expected)",
    Experience: "Experience : Freshers & Experience",
    link: "https://careers.ibm.com/job/19901166/technical-support-engineer-bangalore-in/?codes=SN_LinkedIn&Codes=SN_LinkedIn",
  },
  {
    Name: "Deloitte Careers Fresher Hiring",
    Location: "Location : Mumbai",
    Qualification:
      " Qualification : B.Com / MBA / equivalent qualification/experience",
    link: "https://jobsindia.deloitte.com/job/Mumbai-I-Think-Strategy-Risk-&-Transaction-Forensics-&-Disputes-Fresher-Graduates-Contractual-Role%28Mumbai%29/25355344/",
  },
  {
    Name: "Catchpoint Recruitment 2024 For Systems Engineer",
    Location: "Location : Bengaluru",
    Qualification:
      " Qualification : BE/BTech/MCA Computer Science & Networking,",
    Batch: "Batch : 2022/ 2023",
    Salary: "Salary : Not Disclosed",
    Experience: "Experience : 0 - 1 years",
    link: "https://www.naukri.com/job-listings-systems-engineer-i-catchpoint-systems-inc-bengaluru-0-to-1-years-170624502945?utm_source=jobscoupe.com",
  },
  {
    Name: "KPMG Recruitment 2024 For Audit Analyst",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelor’s Degree",
    Experience: "Experience : 0 – 2 Years",
    link: "https://unstop.com/jobs/risk-advisory-internal-audit-analyst-kpmg-1050319?utm_source=JobScoupe&utm_medium=Affiliates&utm_campaign=KPMG24062024&ref=JobScoupe",
  },
  {
    Name: "Amazon Recruitment 2024 For Transportation Specialist",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : Any Graduate",
    Experience: "Experience : 0 – 5 years",
    link: "https://www.naukri.com/job-listings-transportation-specialist-amazon-hyderabad-0-to-5-years-100624002140?source=jobscoupe.com",
  },
  {
    Name: "Wipro Recruitment 2024 For Data Analyst",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : 2024 ",
    Salary: "Salary : Not Disclosed",
    Experience: "Experience : Freshers / Experience",
    link: "https://unstop.com/jobs/data-analyst-wipro-1054966?utm_source=JobScoupe&utm_medium=Affiliates&utm_campaign=SPG27052024&ref=JobScoupe",
  },
  {
    Name: "Tech Mahindra Recruitment 2024 For Customer Support",
    Location: "Location : Across India (Work From Home)",
    Qualification: " Qualification : Undergraduate / Graduate",
    Batch: "Batch : 2024 ",
    Salary: "Salary : Not Disclosed",
    Experience: "Experience : Freshers",
    link: "https://www.naukri.com/job-listings-tech-mahindra-hiring-for-work-from-home-customer-support-tech-mahindra-hyderabad-0-to-5-years-250624006769?source=jobscoupe.com",
  },
  {
    Name: "Qualcomm Recruitment 2024 For Associate Engineer",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : B.E / B.Tech",
    Batch: "Batch : 2024 ",
    Experience: "Experience : 0 – 1 Year",
    link: "https://unstop.com/jobs/associate-engineer-mst-qualcomm-1054207?utm_source=JobScoupe&utm_medium=Affiliates&utm_campaign=qualcomm23062024&ref=JobScoupe",
  },
  {
    Name: "Qualcomm Off Campus Drive 2024 For Engineering – Internship",
    Location: "Location : Bangalore , Chennai , Noida",
    Qualification: " Qualification : B.E / B.Tech / M.E / M.Tech",
    Batch: "Batch : 2024/ 2025 ",
    Salary: "Salary : Not Disclosed",
    Experience: "Experience : Freshers",
    link: "https://unstop.com/internships/engineering-intern-2024-2025-graduates-qualcomm-951615?utm_source=JobScoupe&utm_medium=Affiliates&utm_campaign=Qualcomm13042024&ref=JobScoupe",
  },
  {
    Name: "Cognizant Recruitment 2024 For Trainee – Junior Data Analyst",
    Location: "Location : Pune",
    Qualification: " Qualification : Graduate / Post Graduate / PhD",
    Batch: "Batch : 2024 ",
    Experience: "Experience : Freshers / Experience",
    link: "https://careers.cognizant.com/global-en/jobs/00059475331/trainee-junior-data-analyst/?source=jobscoupe.com",
  },
  {
    Name: "Standard Chartered Recruitment 2024 For Analyst",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelors / Masters Degree",
    Batch: "Batch : 2024 ",
    Experience: "Experience :  0 – 2 Years",
    link: "https://jobs.standardchartered.com/job/Bangalore-Analyst/797728802/?feedId=363857&source=jobscoupe.com",
  },
  {
    Name: "Urban Company Recruitment 2024 For Software Development Engineer",
    Location: "Location : Gurgaon",
    Qualification: " Qualification : B.E / B.Tech / M.E / M.Tech",
    Batch: "Batch : 2024 ",
    Experience: "Experience : 0 – 2 Years",
    link: "https://unstop.com/jobs/software-development-engineer-1-urban-company-1045839?utm_source=JobScoupe&utm_medium=Affiliates&utm_campaign=UrbanCompany25062024&ref=JobScoupe",
  },
  {
    Name: "Accenture Careers 2024 Hiring For Application Developer",
    Location: "Location : Mumbai",
    Qualification: " Qualification : Bachelor’s/ Master’s degree",
    Batch: "Batch : Recent Batches",
    Salary: "Salary : Up to ₹ 4.5 LPA*",
    Experience: "Experience : Fresher",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4279765-S1651118_en&SRC=RECNau",
  },
  {
    Name: "S and P Global Recruitment Drive 2024 | For Software Development Engineer Apprentice",
    Location: "Location : Ahmedabad",
    Qualification: " Qualification : B Tech",
    Batch: "Batch : Any Batches",
    Salary: "Salary : Up to ₹ 7 – 12 LPA*",
    Experience: "Experience : Fresher",
    link: "https://unstop.com/jobs/software-development-engineer-apprentice-sp-global-1063052?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=SPG29062024&ref=Prepflix",
  },
  {
    Name: "CGI Off Campus Drive 2024 | For Graduate Engineer",
    Location: "Location : Pune",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : Recent Batches",
    Salary: "Salary : ₹ 4 To 9 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://unstop.com/jobs/graduate-engineer-cgi-1063063?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=CGI28062024&ref=Prepflix",
  },
  {
    Name: "BlackRock Off Campus Drive 2024 | For Aladdin Business – Client Service Analyst",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : Recent Batches",
    Salary: "Salary : Up to 4.5 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://unstop.com/jobs/aladdin-business-client-service-analyst-blackrock-1063092?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=BR28062024&ref=Prepflix",
  },
  {
    Name: "Accenture Off Campus Drive 2024 | Hiring For Quality Engineer – Tester",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : Recent Batches ",
    Salary: "Salary : ₹ 4.5 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4366344-S1689605_en&SRC=RECNau",
  },
  {
    Name: "Genpact Hiring Fresher Business Analyst – Software Engineer",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelor’s / Graduation / Equivalent",
    Experience: "Experience : Fresher",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=ANA012784",
  },
  {
    Name: "IBM Freshers Recruitment of Java Software Developer",
    Location: "Location : Multiple Locations",
    Qualification:
      " Required Technical and Professional Expertise : Java Dev: Core Java(8/11/17), Servlet, APIs, JavaScript(Dojo)",
    Batch: "Qualification : Basic Graduation from reputed college ",
    Experience: "Experience : Fresher",
    link: "https://careers.ibm.com/job/20620488/java-developer-remote/?codes=WEB_SEARCH_NA",
  },
  {
    Name: "ABB Recruitment 2024 For R&D Associate Engineer",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : B.E / B.Tech / M.E / M.Tech",
    Batch: "Batch : 2024 ",
    Experience: "Experience : 0 – 2 Years",
    link: "https://unstop.com/jobs/rd-associate-engineer-abb-group-1055652?utm_source=JobScoupe&utm_medium=Affiliates&utm_campaign=ABB24062024&ref=JobScoupe",
  },
  {
    Name: "Hexaware Off Campus Drive 2024 For Infrastructure Management Support",
    Location: "Location : Chennai / Pune / Mumbai / Noida",
    Qualification: " Qualification : Undergraduate / Graduate",
    Batch: "Batch : 2024 ",
    Experience: "Experience : Fresher",
    link: "https://app.joinsuperset.com/join/#/signup/student/jobprofiles/45f5ed91-e4a5-4fc4-a2d8-9cd88836b79c?utm_source=jobscoupe.com",
  },
  {
    Name: "Sony India Recruitment 2024 For AI Intern",
    Location: "Location : Bangalore / Mumbai (Work From Home)",
    Qualification: " Qualification : Bachelor’s / Masters / PhD Degree",
    Experience: "Experience : Freshers / Experience",
    link: "https://www.linkedin.com/jobs/view/3947605417/?utm_source=jobscoupe.com",
  },
  {
    Name: "IQVIA Recruitment 2024 For Junior Data Analyst – Intern",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : B.E / B.Tech",
    Batch: "Batch : 2024 ",
    Experience: "Experience : Freshers / Experience",
    link: "",
  },
  {
    Name: "Citi Off Campus Drive 2024 | Hiring Business Analytics Analyst",
    Location: "Location : Bengaluru",
    Qualification:
      " Qualification : Bachelors/University degree or equivalent experience",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023",
    Salary: "Salary : ₹ 13 LPA (Via Glassdoor)",
    Experience: "Experience : Freshers (0 to 2 years)",
    link: "https://jobs.citi.com/job/bengaluru/analyst-business-analytics/287/66616793472",
  },
  {
    Name: "Diebold Nixdorf Recruitment 2024 For Service Desk",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : Any Graduate",
    Salary: "Salary : Not Disclosed by Recruiter",
    Experience: "Experience : 0 – 4 years",
    link: "https://www.naukri.com/job-listings-service-desk-coordinator-network-support-l1-diebold-nixdorf-india-private-limited-hyderabad-0-to-4-years-100624003204?source=jobscoupe.com",
  },
  {
    Name: "Sopra Steria Recruitment 2024 For Graduate Trainee",
    Location: "Location : Noida",
    Qualification: " Qualification : B.E / B.Tech",
    Batch: "Batch : 2023/ 2024 ",
    Experience: "Experience : 0 – 1 Year",
    link: "https://jobs.smartrecruiters.com/SopraSteria1/743999995772885-engineer-trainee?source=jobscoupe.com",
  },
  {
    Name: "Sopra Steria Recruitment 2024 For Graduate Trainee",
    Location: "Location : Chennai",
    Qualification: " Qualification : B.E / B.Tech",
    Batch: "Batch : 2023/ 2024 ",
    Experience: "Experience : 0 – 1 Year",
    link: "https://jobs.smartrecruiters.com/SopraSteria1/743999995771648-engineer-trainee?source=jobscoupe.com",
  },
  {
    Name: "Sopra Steria Recruitment 2024 For Graduate Trainee",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : B.E / B.Tech",
    Batch: "Batch : 2023/ 2024 ",
    Experience: "Experience : 0 – 1 Year",
    link: "https://jobs.smartrecruiters.com/SopraSteria1/743999995770091-engineer-trainee?source=jobscoupe.com",
  },
  {
    Name: "Capgemini Recruitment 2024 For Accounts Process",
    Location: "Location : Chennai",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 2 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://www.naukri.com/job-listings-openings-for-freshers-in-chennai-capgemini-chennai-0-to-0-years-200624008354?utm_source=jobscoupe.com",
  },
  {
    Name: "IBM Hiring Fresher Drive 2024 | For Internship: Hardware Engineer Intern (Remote)",
    Location: "Location : Remote (Bangalore, Pune & Hyderabad)",
    Qualification: " Qualification : Bachelor’s Or Master’s Degree",
    Batch: "Batch : 2021/ 2022/ 2023/ 2024/ 2025 ",
    Salary: "Salary : 8.4 LPA",
    Experience: "Experience : Fresher",
    link: "https://careers.ibm.com/job/20598558/intern-hardware-engineer-bangalore-in/?codes=Appcast_Indeed_O&ccuid=54777139992&_ccid=1719039626489rldoibxg5&ittk=MDBKIHWTVQ",
  },
  {
    Name: "HCLTech Hiring- SAP Functional Consultant || Job Opportunity",
    Location: "Location : Across India",
    Qualification:
      " Qualification : BE / B.Tech (CSE/IT/ ECE/EEE) Only & B Com (Finance) Only.",
    Batch: "Batch : 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to ₹ 5 LPA*",
    Experience: "Experience : Fresher",
    link: "https://forms.office.com/pages/responsepage.aspx?id=N-edGDrJWk-LaG9MqZQZErhYpJunyJZKqf7OGiCnzjdUQ05CWkhPQUNUTU5TRzNGSUkxTlpOMzFXTC4u",
  },
  {
    Name: "Associate Software Development Engineer NTT",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Bachelor’s degree",
    Experience: "Experience : Freshers / Experienced",
    link: "https://careers.services.global.ntt/global/en/job/NTT1GLOBALR113463EXTERNALENGLOBAL/Associate-Software-Development-Engineer",
  },
  {
    Name: "Accenture Careers 2024 Hiring For Application Developer",
    Location: "Location : Mumbai",
    Qualification: " Qualification : Bachelor’s/ Master’s degree",
    Batch: "Batch : Recent Batches",
    Salary: "Salary : Up to ₹ 4.5 LPA*",
    Experience: "Experience : Fresher",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4279765-S1651118_en&SRC=RECNau",
  },
  {
    Name: "Accenture Careers Fresher & Experience hiring for Operations Engineer",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : BE",
    Experience: "Experience : Minimum 0-2 year(s) of experience is required",
    link: "https://www.accenture.com/in-en/careers/jobdetails?src=LINKEDINJP&id=ATCI-4368126-S1701521_en",
  },
  {
    Name: "Qualcomm Careers Fresher hiring for Interim Engineering Intern",
    Location: "Location : Hyderabad",
    Experience: "Experience : Freshers & Experience",
    link: "https://careers.qualcomm.com/careers/job/446693743471?pid=446693743471&recommended=1",
  },
  {
    Name: "IBM Careers Fresher Hiring: Backend Developer",
    Location: "Location : Bengaluru",
    Experience: "Experience : Freshers & Experience",
    link: "https://careers.ibm.com/job/20432303/backend-developer-bangalore-in/",
  },
  {
    Name: "Wipro Recruitment | Production Agent | Any Graduate/ PG",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : Any Graduate/ PG",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience : 0 – 6 Months",
    link: "https://careers.wipro.com/careers-home/jobs/3080740?lang=en-us&previousLocale=en-US",
  },
  {
    Name: "Accenture Is Hiring For Digital Marketing Associate",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 4.5 LPA (Expected)",
    Experience: "Experience : Fresher (0 – 1)",
    link: "https://www.accenture.com/in-en/careers/jobdetails?src=LINKEDINJP&id=94438_india_2&utm_source=oflatest",
  },
  {
    Name: "Wipro Is Hiring Fresher For Non Voice Process",
    Location: "Location : Chennai",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : As Per Company Standard",
    Experience: "Experience : Fresher (0 – 2)",
    link: "https://www.naukri.com/job-listings-hiring-for-non-voice-process-chennai-wipro-chennai-0-to-2-years-090123005087?utmcampaign=androidjd&utmsource=share&src=sharedjd",
  },
  {
    Name: "Accenture Bulk Hiring For Internship Program 2023",
    Location: "Location : 	Work From Home",
    Qualification:
      " Qualification : BE, B Tech, BA, B COM, BBA, BSC, BCA, ME, M Tech, MCA, MA, M COM, MSC, Any Graduate",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024/ 2025 ",
    Salary: "Salary : Not Mention",
    Experience: "Experience : Fresher",
    link: "https://www.theforage.com/virtual-internships/prototype/PxenP4rHNE6Bh4nQz/Accenture-Nordics-Developer-Virtual-Experience-Program#lp",
  },
  {
    Name: "Hexagon Off Campus Drive 2023 | For Intern",
    Location: "Location : Hyderabad, India",
    Qualification: " Qualification : BE, B Tech, ME, M Tech",
    Batch: "Batch : 2022/ 2023 ",
    Salary: "Salary : Not Mentioned",
    Experience: "Experience : Fresher",
    link: "https://careersindia-hexagon.icims.com/jobs/11018/job?mobile=false&width=1280&height=500&bga=true&needsRedirect=false&jan1offset=330&jun1offset=330",
  },
  {
    Name: "HCL Recruitment Drive 2023 | For Data Analyst",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : Any Degree",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : INR 2.25 LPA*",
    Experience: "Experience : Fresher",
    link: "https://www.naukri.com/job-listings-data-analyst-hyderabad-wfo-hcltech-hyderabad-secunderabad-telangana-0-to-0-years-010823009292?src=jobsearchDesk&sid=16910778505516697&xp=1&px=1",
  },
  {
    Name: "Vistusa Is Hiring For Data Analysis",
    Location: "Location : Hyderabad",
    Qualification:
      " Qualification : BE, B Tech, BA, B COM, BBA, BSC, BCA, ME, M Tech, MCA, MA, M COM, MSC, Any Graduate",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : INR 5.5 LPA to 7.5 LPA",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://www.virtusa.com/careers/in/hyderabad/data-analytics/data-analyst/creq168373",
  },
  {
    Name: "Accenture Hiring Fresher For Customer Service New Associate-Query Management",
    Location: "Location : Gurugram, India.",
    Qualification: " Qualification : Any Graduation",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 3.5 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 1 )",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=269756_india_2&src=LINKEDINJP",
  },
  {
    Name: "Yash Technologies Off Campus 2023 | For Trainee Consultant",
    Location: "Location : Pune",
    Qualification: " Qualification : Any Bachelor’s Degree",
    Batch: "Batch : Any Batches",
    Salary: "Salary : Up to 3.5 LPA (Expected)",
    Experience: "Experience : Fresher (0 – 2)",
    link: "https://careers.yash.com/job/Pune-Trainee-Consultant-SAP-SuccessFactors-Job/942595410/",
  },
  {
    Name: "Amazon Is Hiring Virtual Customer Service",
    Location: "Location : Across India",
    Qualification:
      " Qualification : Min 12th Pass and above (Any Degree/Graduate/Diploma)",
    Batch: "Batch : Any Batches",
    Salary: "Salary : Up to 3.5 - 4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://amazoncustomerservice.hirepro.in/registration/amzcsin/t2g2d/amzcsin/apply/?j=57634&e=13602",
  },
  {
    Name: "GlobalLogic Bulk Hiring 2023 | For Associate Analysts",
    Location: "Location : Gurgaon",
    Qualification:
      " Qualification : BE, B Tech, BA, B COM, BBA, BSC, BCA, ME, M Tech, MCA, MA, M COM, MSC, Any Graduate",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 2.5 - 3 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://careers.hitachi.com/jobs/13184512-associate-analyst-freshers-non-tech-irc191618",
  },
  {
    Name: "KPMG Hiring Freshers 2023 | For Analyst- ServiceNow",
    Location: "Location : Mumbai, India.",
    Qualification: " Qualification : BE, B Tech, ME, M Tech",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 - 7 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/requisitions/preview/INTG1009382/",
  },
  {
    Name: "Google Is Hiring For Network Test Engineer, Global Network Edge",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Any Bachelor’s Degree",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 15 LPA (Expected)",
    Experience: "Experience : 1 Years",
    link: "https://www.google.com/about/careers/applications/jobs/results/125997994655785670-network-test-engineer-global-network-edge?location=India&utm_source=Network_Test_Engineer,_Global_Network_Edge_unstop&utm_medium=listing&utm_campaign=unstop",
  },
  {
    Name: "IBM Is Hiring Associate System Engineer",
    Location: "Location : Bangalore, Gurgaon",
    Qualification: " Qualification : Any Degree",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 8 LPA (Expected)",
    Experience: "Experience : Fresher (0 – 1)",
    link: "https://careers.ibm.com/job/18844416/associate-systems-engineer-remote/?utm_source=Associate_Systems_Engineer_unstop&utm_medium=listing&utm_campaign=unstop",
  },
  {
    Name: "SAP Labs Hiring For Associate",
    Location: "Location : Pune",
    Qualification: " Qualification : Bachelor’s Degree",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : INR 8* KPM",
    Experience: "Experience : Freshers ( 0 – 3 )",
    link: "https://jobs.sap.com/job/Pune-IT-Business-Services-Associate-Consultant-%280-3Y%29-411013/954682301/",
  },
  {
    Name: "Apple Hiring Freshers For Technical Specialist",
    Location: "Location : Pan India",
    Qualification: " Qualification : Bachelor’s degree or Masters",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 - 7 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://jobs.apple.com/en-in/details/200314122/in-technical-specialist?team=APPST",
  },
  {
    Name: "ZOHO Corp Is Hiring For Technical Consultants",
    Location: "Location : Telangana",
    Qualification: " Qualification : Any Degree",
    Batch: "Batch : Any Batches",
    Salary: "Salary : Up to 5.2 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://careers.zohocorp.com/forms/fcc89b5ebd373d598e0224d10f2199d1e70942e4930623c9026f6c67e0713d86",
  },
  {
    Name: "Infosys Hiring Freshers Drive For Process Trainee Roles",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 3.5 LPA (Expected)",
    Experience: "Experience : Fresher/Experienced",
    link: "https://career.infosys.com/jobdesc?source=44003&jobReferenceCode=PROGEN-EXTERNAL-162241",
  },
  {
    Name: "Google Hiring For Software Engineer Intern",
    Location: "Location : Bangalore, Hyderabad, Pune, India.",
    Qualification: " Qualification : Bachelor’s, Master’s or PhD degree ",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 - 7 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://www.naukri.com/chatbot?conversation=marketing_registration&app=Naukri&domain=Naukri&context.src_tmp=12123&utm_source=google&utm_medium=cpc&utm_campaign=Pmax_Metro_Pune_Dec%2722&gclid=EAIaIQobChMIyYDvvc6YgAMVuJBLBR1InwHQEAEYASAAEgKDyvD_BwE",
  },
  {
    Name: "PWC Bulk Hiring 2023 | For Research & Analytics",
    Location: "Location : Bengaluru",
    Qualification:
      " Qualification : BE, BTech, MTech , BSC, Msc, BCA, MCA& Any Graduates",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 6.5 - 9.5 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://pwc.wd3.myworkdayjobs.com/Global_Experienced_Careers/job/Bangalore---RMZ-Hebbal/IFS-Research---Analytics-Services-Research-Hub--Data-Analyst---SA-Blr-Hyd_283575WD?source=172911",
  },
  {
    Name: "Nokia Is Hiring For Automation Engineer",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : 	Any Bachelor’s Or Master’s Degree",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 9 LPA (Expected)",
    Experience: "Experience : Fresher/Experienced",
    link: "https://unstop.com/jobs/automation-engineer-nokia-710705?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=Nokia23072023",
  },
  {
    Name: "Siemens Hiring Fresher For Test Engineer",
    Location: "Location : Goa",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Fresher/Experienced",
    link: "https://unstop.com/jobs/test-engineer-siemens-limited-713093?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=Siemens24072023",
  },
  {
    Name: "Hexaware Mass Walk In Drive 2023 Freshers of Any Degree",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Any Degree",
    Batch: "Batch : Any Batches",
    Salary: "Salary : Up to 2 LPA (Expected)",
    Experience: "Experience : Fresher/Experienced",
    link: "https://www.naukri.com/job-listings-international-voice-process-hexaware-technologies-chennai-tamil-nadu-0-to-0-years-170723004257?xp=6&src=cja1029166&xid=1029166%255Egm%255E53317125&uid=53317125&alertId=&utm_campaign=job_alerts_cja&utm_medium=email&utm_source=joblink&utm_content=4d6f5c1abd6f4bdb3fa9f7f99ed4472fe479887815c553b3",
  },
  {
    Name: "Cisco Hiring For Non Technical Graduate Apprentice",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : BCom, BBA, BA, and BBM",
    Batch: "Batch : 2022/ 2023 ",
    Salary: "Salary : Up to 3 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://jobs.cisco.com/jobs/ProjectDetail/Non-Technical-Graduate-Apprentice-India-UHR/1401472",
  },
  {
    Name: "Tata Power Hiring For Graduate Engineer Trainee – Instrumentation",
    Location: "Location : Across India",
    Qualification: " Qualification : BE, B Tech, BA, BSc, BCom, PGP, MBA",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 6 - 6.4 LPA (Expected)",
    Experience: "Experience : Fresher (0 – 2)",
    link: "https://learning.tcsionhub.in/jobs/Tata-Power-Company-Limited/Graduate-Engineer-Trainee--Instrumentation-5412/",
  },
  {
    Name: "Infosys Is Hiring For Internship | Work From Home",
    Location: "Location : Work  From Home",
    Qualification:
      " Qualification : BE, B Tech, ME, M Tech, MSC, MCA, MBA & PhD",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023/ 2024/ 2025 ",
    Salary: "Salary : INR 20k PM*",
    Experience: "Experience : Fresher",
    link: "https://careers.infosys.com/instep/internship/instepregistrationpage.aspx",
  },
  {
    Name: "Siemens Is Hiring For Customer Service Support Operator",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Any Graduate",
    Batch: "Batch : Any Batches",
    Salary: "Salary : Up to 6.9 LPA (Expected)",
    Experience: "Experience : Fresher/Experienced",
    link: "https://jobs.siemens.com/careers/job/563156116076784",
  },
  {
    Name: "Synopsys Recruitment Drive 2023 | Intern",
    Location: "Location : Noida",
    Qualification: " Qualification : BE, B Tech, ME, M Tech, MCA",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : INR 3* LPA",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25235&siteid=5359&PageType=JobDetails&jobid=1993602#jobDetails=1993602_5359",
  },
  {
    Name: "Accenture Is Hiring For Associate Software Engineer (ASE)",
    Location:
      "Location : Bangalore, Hyderabad, Chennai, Mumbai, Pune, Gurugram",
    Qualification:
      " Qualification : 	BE, BTech, BSc, BCA, BCom, BBA, BA, M.E, MCA, MSc & Any Graduates",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : INR4.2 – 4.5 * LPA",
    Experience: "Experience : Fresher",
    link: "https://indiacampus.accenture.com/myzone/accenture/1/jobs/2211/job-details",
  },
  {
    Name: "Concentrix Is Hiring For Voice / Non – Voice | Immediately Exam",
    Location: "Location : Across India",
    Qualification: " Qualification : 12th Pass, Any Diploma, Any Graduate",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Not Mentioned",
    Experience: "Experience : Fresher",
    link: "https://concentrix.myamcat.com/register?data=GBGzaOLVedj3MmBrnndC0cW%2F0nKr9ErGpe0b6rqO1WmjHns6K7CQ4Jp1c0ZyUnJt%2BUdOoWdu%2BPOgeD57TKxX3%2Bu4U1aQoLdZTuShSAt%2BC9K%2FOOAzTQ%2FKdpFe2EXAFBll",
  },
  {
    Name: "Wipro Hiring For School of IT Infrastructure Management – 2023",
    Location: "Location : Pan India",
    Qualification: " Qualification : Any Diploma",
    Batch: "Batch : 2021/ 2022/ 2023 ",
    Salary: "Salary : INR 12.4K To 19.6K PM",
    Experience: "Experience : Fresher",
    link: "https://app.joinsuperset.com/join/#/signup/student/jobprofiles/f2a20a8a-fae0-4281-9c52-19317da99bb1",
  },
  {
    Name: "Shell Hiring Fresher For Engineer PMO Asset – Support",
    Location: "Location : Chennai",
    Qualification: " Qualification : BE, B Tech, ME, M Tech",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 10 LPA (Expected)",
    Experience: "Experience : Fresher (0 – 2)",
    link: "https://unstop.com/jobs/engineer-pmo-asset-support-shell-708167?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=Shell20072023",
  },
  {
    Name: "Genpact Recruitment Drive 2023 For Associate",
    Location: "Location : Gurgaon",
    Qualification: " Qualification : Bachelor’s or Master’s degrees",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 3.5 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=ANA008493",
  },
  {
    Name: "Infosys Bulk Hiring 2023 | For Process Executive",
    Location: "Location : Bengaluru",
    Qualification:
      " Qualification : BE, BTech, MTech , BSC, Msc, BCA, MCA& Any Graduates",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 4.2 - 5.5 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://career.infosys.com/jobdesc?jobReferenceCode=PROGEN-EXTERNAL-152939&source=44003",
  },
  {
    Name: "Cognizant Hiring Freshers For TECHNOLOGY SPECIALIST",
    Location: "Location : Bangalore, Hyderabad, Pune, India.",
    Qualification: " Qualification : BSC, BCOM, BE, Diploma Degrees",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 4 - 6 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://careers.cognizant.com/in/en/job/COGNGLOBAL00047698001/Technology-Specialist?utm_source=linkedin&utm_medium=phenom-feeds",
  },
  {
    Name: "Tata International Bulk Hiring  2023 | For Graduate Engineer Trainee",
    Location: "Location : Ludhiana & Ranipet",
    Qualification: " Qualification : BE, B Tech, ME, M Tech, MCA, Any Graduate",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 5 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://myhub.tatainternational.com/RVW/hub/index.html?RVWRTQS_REQID=75d1946c-41fa-4fc0-9a2a-f800ababa9f3&bl=en-us&_dc=1689734564228",
  },
  {
    Name: "Norton LifeLock Is Hiring For Software Engineer",
    Location: "Location : Chennai",
    Qualification: " Qualification : BS, MS, BE, B Tech, ME, M Tech",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 9 LPA (Expected)",
    Experience: "Experience : 	Fresher (0 – 3)",
    link: "https://unstop.com/jobs/software-engineer-norton-lifelock-707352?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=NortonLifelock19072023",
  },
  {
    Name: "Ericsson Recruitment Drive 2023 | For DevOps Engineer",
    Location: "Location : Gurgaon",
    Qualification: " Qualification : Bachelor’s and master’s degrees",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 8.8 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://jobs.ericsson.com/job/Gurgaon-DevOps-Engineer-Hary/770381302/",
  },
  {
    Name: "Cyient Off Campus Drive For Engineer – Entry",
    Location: "Location : Mumbai",
    Qualification: " Qualification : Bachelor’s Degree",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://cyient.wd3.myworkdayjobs.com/en-US/careers/job/Engineer---Entry_JR-043700",
  },
  {
    Name: "Oracle Hiring For Accounting Support",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Graduate, Post Graduate",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 5.6 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/requisitions/preview/207711/?lastSelectedFacet=POSTING_DATES&selectedFlexFieldsFacets=%22AttributeChar6%7C0+to+2%2B+years%22&selectedLocationsFacet=300000000106947&selectedPostingDatesFacet=7",
  },
  {
    Name: "KPIT Technologies is hiring for System Engineering",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : Any Graduation",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://talentojo.kpit.com/tojo/app/job-apply/#/Career%20Portal/47784?utm_source=LinkedIn&utm_campaign=brand&utm_medium=job_board",
  },
  {
    Name: "IBM Hiring For the position of Software Engineer",
    Location: "Location : 	Bangalore, Pune, Hyderabad",
    Qualification: " Qualification : Any Bachelor’s Degree",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 9 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://unstop.com/jobs/software-engineer-ibm-706460?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=IBM18072023",
  },
  {
    Name: "Cognizant Bulk Hiring 2023 | Permanent Work From Home",
    Location: "Location : WFH",
    Qualification:
      " Qualification : BE, BTech, BSc, BCA, BCom, BBA, BA, M.E, MCA, MSc & Any Graduates",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://www.naukri.com/job-listings-cognizant-is-hiring-freshers-non-voice-voice-hyderabad-cognizant-hyderabad-secunderabad-0-to-0-years-310123018939?src=firstnaukri&utm_source=firstnaukri&utm_medium=jd",
  },
  {
    Name: "Bajaj Finserv is hiring for Trainee Technology",
    Location: "Location : Pune",
    Qualification: " Qualification : BE/ BTech/ MS",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : 0 – 2 Years",
    link: "https://apps600.tcsprocesscloud.in/webhcm/bfl/careers?jobReqId=117506",
  },
  {
    Name: "Deloitte is hiring for Business Technology Analyst",
    Location: "Location : Bengaluru/Hyderabad",
    Qualification: " Qualification : BE/ B.Tech",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 10 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://usijobs.deloitte.com/careersUSI/JobDetail/USI-EH24-Tax-GESTC-GA-BISO-BTA/140767",
  },
  {
    Name: "Cognizant is hiring for Associate",
    Location: "Location : Chennai",
    Qualification: " Qualification : Graduate / Engineering graduate",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022",
    Salary: "Salary : Up to 6.5 LPA (Expected)",
    Experience: "Experience : 0 – 4 Years",
    link: "https://careers.cognizant.com/in/en/job/COGNGLOBAL000426857022/Associate",
  },
  {
    Name: "EY Recruitment Drive 2023 | For Data Analytics",
    Location: "Location : Bengaluru",
    Qualification:
      " Qualification : BE, BTech, ME, MTech, MCA, MS, Any Graduate",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 8.8 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://eyglobal.yello.co/jobs/WtNpmD7VxdReNK_DleZg1w?job_board_id=c1riT--B2O-KySgYWsZO1Q",
  },
  {
    Name: "ZOHO Is Hiring For Software Developer",
    Location: "Location : Tamil Nadu",
    Qualification: " Qualification : BE, B Tech, ME, M Tech, MSC & MCA",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://unstop.com/jobs/software-developer-zoho-705386?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=Zoho16072023",
  },
  {
    Name: "Infosys Hiring Freshers For Junior Accountant",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : B.com, MBA – Finance, M.com",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022",
    Salary: "Salary : Up to 3.6 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://career.infosys.com/jobdesc?jobReferenceCode=PROGEN-EXTERNAL-161813",
  },
  {
    Name: "Apple is hiring for Business Expert",
    Location: "Location : Across India",
    Qualification: " Qualification : Bachelor’s/ Master’s Degree/ MBA",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 12 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://jobs.apple.com/en-us/details/200313970/in-business-expert",
  },
  {
    Name: "Vodafone Idea is hiring for Manager – Activation Officer",
    Location: "Location : Guwahati",
    Qualification: " Qualification : Any Graduation ",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://careers.vodafoneidea.com/job/Manager-Activation-Officer/892382701/",
  },
  {
    Name: "Teleperformance is hiring for Digital Relationship Executives",
    Location:
      "Location : Noida, Gurgaon, Kolkata, Mumbai, Bangalore, Ahmedabad & Hyderabad",
    Qualification: " Qualification : Graduate/ Undergraduates",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://www.teleperformance.com/en-us/job-opportunities/india/digital-relationship-executives-work-from-home/",
  },
  {
    Name: "Groww is hiring for Customer Success Executive",
    Location: "Location : Across India",
    Qualification: " Qualification : B.Com/ BBA/ BBM/ BA/ B.Sc/ MBA/ PGDM",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://groww.skillate.com/jobs/48138",
  },
  {
    Name: " Webunity infotech",
    Location: "Role  - Andriod Developer",
    Qualification: " Qualification : Bachelor’s Degree",
    Salary: "Salary : Up to 10 LPA (Expected)",
    link: "https://www.offcampusitjob.com/index.php/2023/07/15/webunity-infotech-andriod-developer10-lpab-tech/",
  },
  {
    Name: "Allerin is hiring for Trainee Test Engineer",
    Location: "Location : Mumbai",
    Qualification: " Qualification : B.E/ B.Tech/ B.Sc/ BCA",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://www.allerin.com/careers/trainee-test-engineer",
  },
  {
    Name: "LG Soft is hiring for Research Engineer",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : B.E./ B.Tech/ M.Tech",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 10 LPA (Expected)",
    Experience: "Experience : 0 -1 Year",
    link: "https://www.naukri.com/job-listings-research-engineer-lg-soft-india-bangalore-bengaluru-karnataka-0-to-1-years-170623003632",
  },
  {
    Name: "TCS Walk-in Drive for Back-office operations",
    Location: "Location : Across India",
    Qualification: " Qualification : B.Com/ BA/ BBA/ BMS/ BBM/ B.Sc/ BCA",
    Batch: "Batch : 2021/ 2022 ",
    Salary: "Salary : Up to 3.4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://nextstep.tcs.com/campus/#/",
  },
  {
    Name: "Infosys Is Hiring For Internship | Work From Home",
    Location: "Location : Work From Home",
    Qualification:
      " Qualification : BE, B Tech, ME, M Tech, MSC, MCA, MBA & PhD",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023/ 2024/ 2025 ",
    Salary: "Salary : INR 20k PM (Expected)",
    Experience: "Experience : Fresher",
    link: "https://careers.infosys.com/instep/internship/instepregistrationpage.aspx",
  },
  {
    Name: "Amazon Hiring For Support Analyst",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : 	Bachelor’s Degree",
    Batch: "Batch : Not Mentioned  ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/ju0f4/apply/?j=56343&e=12198",
  },
  {
    Name: "Cognizant Bulk Hiring 2023 | For Programmer Analyst Trainee",
    Location: "Location : Pan India",
    Qualification: " Qualification : BE, BTech, ME, MTech, BCA, MCA, MSc",
    Batch: "Batch : 2023 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience : 	Fresher(0-2 )",
    link: "https://app.joinsuperset.com/company/cognizant/WestandCentralColleges.html",
  },
  {
    Name: "Siemens Is Hiring For Graduate Engineer Trainee",
    Location: "Location : Across India",
    Qualification: " Qualification : 	Bachelor’s Or Master’s Degree",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023",
    Salary: "Salary : Up to 3.6 LPA (Expected)",
    Experience: "Experience : Fresher (0 – 1)",
    link: "https://jobs.siemens.com/careers?query=graduate%20engineer%20trainee&location=India&pid=563156115975809&domain=siemens.com&sort_by=relevance&triggerGoButton=true",
  },
  {
    Name: "Rockwell Automation Is Hiring For Test Automation Engineer",
    Location: "Location : Pune",
    Qualification: " Qualification : 	Any Bachelor’s Or Master’s Degree",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "https://jobs.rockwellautomation.com/job/13531045/test-automation-engineer-pune-in/",
  },
  {
    Name: "Nagarro Bulk Hiring 2023 | For Work From Home",
    Location: "Location : Work From Home",
    Qualification: " Qualification : 	Any Degree",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 3.5-6 LPA (Expected)",
    Experience: "Experience : Freshers",
    link: "https://jobs.smartrecruiters.com/Nagarro1/743999905723747-trainee",
  },
  {
    Name: "Cognizant Hiring For Associate| One of the Highest-paying job in IT",
    Location: "Location : Bengaluru",
    Qualification: " Qualification :  BE, B Tech, MCA",
    Batch: "Batch : Not Mentioned",
    Salary: "Salary : Up to 3.4 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 2 )",
    link: "hhttps://careers.cognizant.com/in/en/job/COGNGLOBAL00052479211/Associate?utm_source=linkedin&utm_medium=phenom-feeds",
  },
  {
    Name: "Wipro Is Hiring For Data Analytics",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : 	Any Degree Graduate",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 7 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://www.naukri.com/job-listings-mega-hiring-for-foreign-language-wipro-wipro-hyderabad-secunderabad-0-to-3-years-060423005125?src=jobsearchDesk&sid=16863944698362302&xp=7&px=1&nignbevent_src=jobsearchDeskGNB",
  },
  {
    Name: "Siemens Recruitment Drive 2023 | For Graduate Trainee Engineer",
    Location: "Location : Gurgaon",
    Qualification: " Qualification : BE, BTech, MCA",
    Batch: "Batch : Not Mentioned",
    Salary: "Salary : Up to 5.4 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 1 )",
    link: "https://jobs.siemens.com/careers/job/563156115968728",
  },
  {
    Name: "PTC Recruitment Drive 2023 | For Cloud Service Operations Engineer, Associate",
    Location: "Location : Pune",
    Qualification: " Qualification : BE, B Tech, ME, M Tech, MCA",
    Batch: "Batch : Not Mentioned",
    Salary: "Salary : Up to 7 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://ptc.eightfold.ai/careers/job/137454553523?",
  },
  {
    Name: "Velotio Is Hiring For Work From Home ",
    Location: "Location : Work From Home",
    Qualification: " Qualification :  BE, BTech, ME, MTech or equivalent",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 5.4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://apply.workable.com/velotio/j/84BEC7BE03/",
  },
  {
    Name: "HPE Hiring Freshers 2023 | For Software Engineer",
    Location: "Location : Bengaluru",
    Qualification: " Qualification : 	Bachelor’s Degree",
    Batch: "Batch : Not Mentioned ",
    Salary: "Salary : Up to 4-7 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://careers.hpe.com/us/en/job/HPE1US1150170EXTERNALENUS/Software-Engineer",
  },
  {
    Name: "HCL Tech Is Hiring For Data Analyst",
    Location: "Location : Chennai",
    Qualification: " Qualification : Any Degree",
    Batch: "Batch : 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Based In Industry",
    Experience: "Experience :  Fresher / Experienced",
    link: "https://www.linkedin.com/jobs/view/3611213253/",
  },
  {
    Name: "Infosys BPM Recruitment Drive 2023 | For Systems Engineer IT Service Management",
    Location: "Location : Bengaluru",
    Qualification: " Qualification :  Any Graduate",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 3.5 LPA (Expected)",
    Experience: "Experience :  0-4 Year",
    link: "https://www.linkedin.com/jobs/view/3515827322/",
  },
  {
    Name: "Dishtv is hiring for Inbound Calls",
    Location: "Location : Work From Home",
    Qualification: " Qualification : Any Graduation",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Freshers",
    link: "https://www.dishtv.in/pages/others/dishtv-freelance-jobs.aspx",
  },
  {
    Name: "ICICI Bank is hiring for Information Technology Analyst",
    Location: "Location : Bengaluru/ Mumbai/ Hyderabad",
    Qualification: " Qualification : Graduate/ MBA/ MCA",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 8 LPA (Expected)",
    Experience: "Experience :  0-5 Year",
    link: "https://www.icicicareers.com/website/Jobs/Hot-Jobs/2025789.html",
  },
  {
    Name: "Deloitte is hiring for Executive Assistant",
    Location: "Location : Mumbai",
    Qualification: " Qualification : B.A/ B.Com",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Freshers",
    link: "https://jobsindia.deloitte.com/job/Mumbai-Tax-Executive-Assistant-Mumbai-1/15885144/",
  },
  {
    Name: "Accenture Hiring For System and Application Services Associate",
    Location: "Location : Bangalore",
    Qualification: " Qualification : Bachelor’s Degree",
    Batch: "Batch : 2023 ",
    Salary: "Salary : Up to 3.4 LPA (Expected)",
    Experience: "Experience : Freshers ( 0 – 11 Months )",
    link: "https://indiacampus.accenture.com/myzone/accenture/1/jobs/3627/job-details",
  },
  {
    Name: "Mercedes Benz is hiring for Intern",
    Location: "Location : Work From Home",
    Qualification: " Qualification : Engineering",
    Batch: "Batch : 2023/ 2024/ 2025 ",
    Salary: "Salary : Up to 40K Per Month (Expected)",
    Experience: "Experience : Freshers",
    link: "https://jobs.mercedes-benz.com/job/379864/intern-2023.html",
  },
  {
    Name: "TCS Is Hiring For Back office operations",
    Location: "Location : Across India.",
    Qualification: " Qualification : B.com, BBA, BA, B.sc",
    Batch: "Batch : Not Mentioned  ",
    Salary: "Salary : Up to 3-4 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://www.linkedin.com/posts/joyal-johnson_thebigmove-freshershiring-tcsahmedabad-activity-7071823057480257536-NVZA/",
  },
  {
    Name: "Cognizant Hiring Fresher Drive 2023 | For Junior Data Analyst",
    Location: "Location : Coimbatore",
    Qualification: " Qualification : 	Any Degree",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 3.6 LPA (Expected)",
    Experience: "Experience : Fresher (0 -1) Year",
    link: "https://careers.cognizant.com/studentandinterns/in/en/job/00043576146/Trainee-Junior-Data-Analyst",
  },
  {
    Name: " GE (General Electric) Is Hiring For Services Specialist - SCADA",
    Location: "Location : Noida",
    Qualification: " Qualification : B.E/ B. Tech",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024  ",
    Salary: "Salary : Up to 9 LPA (Expected)",
    Experience: "Experience :  Fresher (0 -1) Year",
    link: "https://unstop.com/jobs/software-specialist-scada-ge-digital-685152?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=GE08062023",
  },
  {
    Name: "Adani Is Hiring For Graduate Engineer Trainee",
    Location: "Location : Ahmadabad",
    Qualification: " Qualification : B.E/ B. Tech",
    Batch: "Batch : Not Mentioned",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://adani.taleo.net/careersection/ex/jobdetail.ftl?job=2200032S&lang=en",
  },
  {
    Name: "Tata Power Recruitment Drive 2023 | For Graduation Engineer Trainee",
    Location: "Location : Pan India",
    Qualification: " Qualification : BE, BTech, BA, BCom, MBA",
    Batch: "Batch : Not Mentioned",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://learning.tcsionhub.in/jobs/Tata-Power-Company-Limited/Graduate-Engineer-Trainee--Fire--Safety-4806/",
  },
  {
    Name: "Yash Technologies is hiring for Test Engineer",
    Location: "Location : Pune",
    Qualification: " Qualification :  Bachelor’s or Master’s Degree",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Freshers",
    link: "https://careers.yash.com/job/Pune-Test-Engineer-Web-Automation-testing-Selenium-Job/939991810/?utm_source=jssc.in",
  },
  {
    Name: "Amazon Is Hiring For QA Engineer",
    Location: "Location : Chennai",
    Qualification: " Qualification : Graduation",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022 ",
    Salary: "Salary : Up to 4-7 LPA (Expected)",
    Experience: "Experience : Fresher",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/ju0f4/apply/?j=56341&e=12178",
  },
  {
    Name: "GE (General Electric) Is Hiring For Engineer 1 - Electronic Hardware",
    Location: "Location : Chennai",
    Qualification: " Qualification : Any Degree",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024 ",
    Salary: "Salary : Up to 9 LPA (Expected)",
    Experience: "Experience : Fresher (0 -1) Year",
    link: "https://unstop.com/jobs/engineer-1-electronic-hardware-ge-power-india-limited-685765?utm_source=Prepflix&utm_medium=Affiliates&utm_campaign=GE06062023",
  },
  {
    Name: "Fujitsu Off Campus Drive 2023 | For Intern",
    Location: "Location : Across India",
    Qualification: " Qualification : B.E/ B. Tech",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience :  Fresher (0 -1) Year",
    link: "https://fujitsu.ripplehire.com/candidate/?token=GnERdkVEzsh4wo2QUySO&lang=en&source=LINKEDIN&ref=LI02#detail",
  },
  {
    Name: "Siemens is hiring for Software Developer",
    Location: "Location : Bangalore",
    Qualification: " Qualification : B.E/ B. Tech/ MCA/ M.E/ M. Tech/ MSc",
    Batch: "Batch : 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 10 LPA (Expected)",
    Experience: "Experience :  0-1 Year",
    link: "https://jobs.siemens.com/careers/job/563156115937902?domain=siemens.com&hl=en",
  },
  {
    Name: "Zycus is hiring for Analyst",
    Location: "Location : Bengaluru/ Mumbai/ Pune",
    Qualification: " Qualification :  B.E/ B.Tech",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience :  0-4 Year",
    link: "https://zycus.skillate.com/jobs/44616",
  },
  {
    Name: "PwC is hiring for Web Developer",
    Location: "Location : Remote",
    Qualification: " Qualification :  Bachelor’s  Degree",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 10 LPA (Expected)",
    Experience: "Experience : Freshers",
    link: "https://www.pwc.com/gx/en/careers/experienced-job-search/description.html?wdjobreqid=259333WD",
  },
  {
    Name: "Conduent is hiring for IT Testing Engineer",
    Location: "Location : Hyderabad",
    Qualification: " Qualification : BE/ B.Tech/ B.Sc/ BCA",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 6 LPA (Expected)",
    Experience: "Experience : Freshers",
    link: "https://professional-enjobs-conduent.icims.com/jobs/80126/job?mobile=false&width=1178&height=500&bga=true&needsRedirect=false&jan1offset=330&jun1offset=330",
  },
  {
    Name: "Iris is hiring for Data Engineer",
    Location: "Location : Noida",
    Qualification: " Qualification : B.E/ B.Tech/ M.E/ M.Tech",
    Batch: "Batch : 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 10 LPA (Expected)",
    Experience: "Experience :  0-2 Year",
    link: "https://careers.irissoftware.com/job/Noida-Data-Engineer/14650044/",
  },
  {
    Name: "Amazon is hiring for Seller Support Associate",
    Location: "Location : Bangalore",
    Qualification: " Qualification :  Any Graduation/ Post Graduation",
    Batch: "Batch : 2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023 ",
    Salary: "Salary : Up to 4 LPA (Expected)",
    Experience: "Experience :  0-5 Year",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/ju0f4/apply/?j=57622&e=13588",
  },
];
